apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-y1b8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-y1b8
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-y1b8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-y1b8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-y1b8
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yjkf-tenant/rhtap-demo-app/hacbs-test-project-y1b8@sha256:8c379ed916d4f12470aee33d16aeab53c4a160fe32a92f4e83b5868bce53619b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
